#!/usr/bin/env bash
# Configures local IP mappings for localhost and facebook.com in /etc/hosts

# 127.0.0.1 localhost sətrini təmizləyirik və yeni xəritəni əlavə edirik
grep -v "127.0.0.1 localhost" /etc/hosts | grep -v "facebook.com" > /tmp/hosts.tmp
echo "127.0.0.2 localhost" >> /tmp/hosts.tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts.tmp

# Hazır mətni tək bir toxunuşla /etc/hosts faylına yazırıq (Bu zaman busy xətası vermir)
cat /tmp/hosts.tmp > /etc/hosts
rm /tmp/hosts.tmp